# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Umami Kotlin
site_url: https://umami-kotlin.appoutlet.dev
repo_url: https://github.com/AppOutlet/umami-kotlin
repo_name: AppOutlet/umami-kotlin
theme:
  name: material
  palette:
    primary: 'deep purple'
    accent: 'indigo'
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - search.suggest
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

nav:
  - Overview: index.md
  - Roadmap: roadmap.md
  - API Reference: reference

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - search