name: Verify

on:
  pull_request:
    branches:
      - '**'

jobs:
  publish-artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: 'on-failure'
          cache-read-only: false

      - name: Run detekt
        run: ./gradlew detekt